---
- name: Disable QRadar Rule to Trigger an Offense
  hosts: all
  collections:
    - ibm.qradar

  tasks:
    - name: Get Rule ID for "{{ qradar_rule_name }}"
      qradar_rule_info:
        name: "{{ qradar_rule_name }}"
      register: qrule_info

    - debug:
        var: qrule_info

    - name: Disable Rule "{{ qradar_rule_name }}"
      qradar_rule:
        id: "{{ qrule_info['rules'][0]['id'] }}"
        state: disabled


